### PR TITLE
Add `parallel_apply` for `Resampler` class

### PR DESCRIPTION
**Pull request by alvail**
I implemented `parallel_apply` for the `Resampler` class to have some important time series functionality. For now it is still using the default `_chunk` method, but it can lead to some processes terminating much quicker than others i.e. if the time series gets denser over time. A potential upgrade would be to random sample the contents of the chunks, so each chunk gets a similar distribution of workloads.

P.S.: I noticed that 30/188 of the tests fail due to a `ZeroDivisionError`. This is unrelated to my pull request, but an important issue.

### CODE REVIEW

**Comment by till-m** [comment]
Hey @alvail,

this is pretty cool, thanks for contributing!
This looks really good imo, no comments on the code. However, could you add a few more tests to increase coverage of `resampler.py`?

>  I noticed that 30/188 of the tests fail due to a `ZeroDivisionError`.

This has been an issue for a bit (#184) and is the reason why GH actions currently doesn't run the tests on windows Unfortunately I don't have access to a windows machine.

**Comment by alvail** [comment]
Hello @till-m,

I added some test coverage, fixed some bugs and clean up the code. I am on Windows and only getting the usual `ZeroDivisionError` . The metadata wrapping might not be perfect for `Series`  objects, because the `_wrap_result()` method does not defer the sampling frequency and data frame source column name to the parallel result in at least one case. When testing this the equals assertion is still holding though. This is something to improve, even though it might be less important.

**Comment by alvail** [comment]
The `pandas==1.0.5` tests failed, because this pandas version cannot handle an apply specifying a column. Why that is not the case for later versions I do not understand. I think I found the culprit source code leading to this error ([1](https://github.com/pandas-dev/pandas/blob/8dab54d6573f7186ff0c3b6364d5e4dd635ff3e7/pandas/core/resample.py#L343-L358), [2](https://github.com/pandas-dev/pandas/blob/8dab54d6573f7186ff0c3b6364d5e4dd635ff3e7/pandas/core/resample.py#L428), [3](https://github.com/pandas-dev/pandas/blob/8dab54d6573f7186ff0c3b6364d5e4dd635ff3e7/pandas/core/groupby/generic.py#L998)) and it did not change for later pandas versions. Because this has nothing to do with my implementation, I handled that edge case with an if statement.

I also noticed some minor differences in outputs. For example an integer column in the input might result in an float column in the output, leading to a failed test. E.g. when doing `df.iloc[0]` the row is returned as a series with the lowest restrictive common data type, which is float when having integer and float columns. Because output types and columns can be arbitrary, I can not not just set the same column types as the input data frame to deal with that. Any hints or help would be highly appreciated here. I removed any tests which in apply return a mix of integer an float columns for now.

Also I added an additional test for when a series is returned from the apply function.

**Comment by nalepae** [comment]
@alvail , I fixe `ZeroDivisionError` on Windows with this PR: https://github.com/nalepae/pandarallel/pull/212

However, I don't have access to a Windows machine (and because I'm using an ARM M1 Macbook, I even struggle to run Windows on a virtual machine).

If you could install the **pandarallel** version of the branch of the PR  https://github.com/nalepae/pandarallel/pull/212 and run all examples of https://github.com/nalepae/pandarallel/blob/master/docs/examples_windows.ipynb with `pandarallel.initialize(progress_bar=True)`, then tell me if everything is fine (or not) it would be super nice!

**Comment by alvail** [comment]
I had to fix the testing code, because I forgot to copy paste the correct tests.

When testing #212 through the notebook with `progress_bars=True` the progress bars were not shown. The test environment was created with `conda`. I installed the 197 branch from the archive, `ipykernel`, `ipywidets` and ran the notebook in VS Code.

**Comment by nalepae** [comment]
@alvail it is `progress_bar=True` (without `s` at progress).
Did you already see progress bars working on Windows?

**Comment by alvail** [comment]
@nalepae actually my screenshot of them working does not mean anything, because the input was not the same as in the tests. Even back then the tests might have failed. Generally the progress bars still work and always worked for me on Windows, except for some edge cases like the tests.

**Comment by till-m** [comment]
Hi @alvail, could you merge the upstream changes into your branch so that I can run the windows tests?

**Comment by till-m** [comment]
bump @alvail

**Comment by alvail** [comment]
@till-m merged it

**Comment by till-m** [comment]
Looks like pandas 1.0.5 is incompatible with numpy >1.23 -- [jobs that used to pass fail now.](https://github.com/nalepae/pandarallel/actions/runs/3630996878/jobs/6383156433).
I will exclude the combination of Python 3.8.10/Pandas 1.0.5.

**Comment by till-m** [comment]
@alvail could you merge upstream again? I think after this we should be ready to merge.

**Comment by till-m** [comment]
I will merge this PR soon unless there are any objections :)

**Comment by nalepae** [comment]
Yes please!

I'll try to release a new version of `pandarallel` this week.

**Comment by till-m** [comment]
Thanks for your contribution! :)

**Comment by nalepae** [comment]
@alvail , when I try the following code:

```python
df_size = int(1e3)
    
df = pd.DataFrame(
    dict(
        b=np.random.rand(df_size),
        c=np.random.rand(df_size),
    ),
    index=pd.to_datetime(np.arange(df_size), unit="m")
)

def func(x):
    return sum(x)**2

res = df.resample("h").apply(func) # OK
res_parallel = df.resample("h").parallel_apply(func) # NOK
```

 the `pandas` version works well, but with `pandarallel` I get the following error:

```python
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/manu/.pyenv/versions/3.10.5/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/manu/.pyenv/versions/3.10.5/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/manu/Perso/pandarallel/pandarallel/core.py", line 160, in __call__
    results = self.work_function(
  File "/Users/manu/Perso/pandarallel/pandarallel/data_types/resampler.py", line 39, in work
    return [compute_result(key, df) for key, df in data]
  File "/Users/manu/Perso/pandarallel/pandarallel/data_types/resampler.py", line 39, in <listcomp>
    return [compute_result(key, df) for key, df in data]
  File "/Users/manu/Perso/pandarallel/pandarallel/data_types/resampler.py", line 34, in compute_result
    result = user_defined_function(
  File "/var/folders/q6/4shqb19d5zn04_rk14bld7dr0000gn/T/ipykernel_13658/1029604941.py", line 157, in func
TypeError: unsupported operand type(s) for +: 'int' and 'str'
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
File <timed exec>:1, in <module>

File ~/Perso/pandarallel/pandarallel/core.py:446, in parallelize_with_pipe.<locals>.closure(data, user_defined_function, *user_defined_function_args, **user_defined_function_kwargs)
    443     elif worker_status == WorkerStatus.Error:
    444         progress_bars.set_error(worker_index)
--> 446 results = results_promise.get()
    448 return data_type.reduce(results, reduce_extra)

File ~/.pyenv/versions/3.10.5/lib/python3.10/multiprocessing/pool.py:771, in ApplyResult.get(self, timeout)
    769     return self._value
    770 else:
--> 771     raise self._value

TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

Could you please have a look?
(Meanwhile I'll revert your changes, so I can release a new `pandarallel` version)

**Pull request merged**
