### PR TITLE
Fix ValueError for Empty DataFrames: Ensure Process Count is at Least 1

### LINKED ISSUE #115: parallel_apply on empty dataframe fails with confusing error
I occasionally have code that should fail earlier because I've accidentally created an empty dataframe, however I've found that `parallel_apply` fails when `apply` does not on these, with an error from `multiprocessing`. I'm not sure if the desired behavior for `parallel_apply` on an empty dataframe is for it to fail, but if it is then it would be nice to have that explicitly handled as it can be rather confusing to figure out what's going on.

Here's a [gist](https://gist.github.com/zachary-jablons-okcupid/9c0e48b0eae286d585443e5030a77f5f) that reproduces this issue, and the error that I get is below:
```
INFO: Pandarallel will run on 48 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
Traceback (most recent call last):
  File "empty_error.py", line 13, in <module>
    pandarallel_apply = empty_df.a.parallel_apply(lambda x: x + 1)
  File "/home/u1/zach/.pyenv/versions/py37/lib/python3.7/site-packages/pandarallel/pandarallel.py", line 447, in closure
    nb_workers, worker_init, (prepare_worker(use_memory_fs)(worker),),
  File "/home/u1/zach/.pyenv/versions/3.7.5/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/u1/zach/.pyenv/versions/3.7.5/lib/python3.7/multiprocessing/pool.py", line 169, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```

It's not obvious that this error is due to an empty dataframe. I think what happens is that `nb_workers` is set to `0` [here](https://github.com/nalepae/pandarallel/blob/master/pandarallel/pandarallel.py#L443).

This is on Python 3.7.5 with
```
pandas==1.1.3
pandarallel==1.5.1
```

Thanks,
Zach

### LINKED ISSUE #141: ValueError: Number of processes must be at least 1
[6887] Failed to execute script sbp
Traceback (most recent call last):
  File "sbp.py", line 565, in <module>
  File "pandarallel/pandarallel.py", line 447, in closure
  File "multiprocessing/context.py", line 119, in Pool
  File "multiprocessing/pool.py", line 169, in __init__
ValueError: Number of processes must be at least 1

### PR DESCRIPTION
**Pull request by Mithil467**
Since nb_item comes out as 0 for empty dataframes and series, we were returning an empty list from the `chunk` function.
Hence, we were yielding nothing from our `DataType.get_chunks` method which caused our `chunks` list being empty and nb_workers = len(chunks) = 0.

Let me know if this fix seems good enough, and also if we need to add any new tests.

Fixes #115, fixes #141.

### CODE REVIEW

**Comment by till-m** [comment]
Hi @Mithil467,

thanks for the PR. Could you please add a test for this case?

**Comment by Mithil467** [comment]
Sure. I noticed that when progress_bar is True, we get ZeroDivisionError. In order to fix that, I would need to know what we expect UI wise. I personally like [2] more than [1] as it gives a sense of success, but would like to know your opinions or if you want to do things differently.

Consoles:

1. image
2. image

Notebook:

1. image
2. image

**Comment by till-m** [comment]
Personally, I prefer option 1.: The grey bar is neither failure (red) nor success (green), similarly, the processing of the empty DataFrame didn't really succeed or fail.
@nalepae do you have an opinion on the matter?

**Comment by Mithil467** [comment]
@till-m @nalepae If you say so, I can make the necessary changes to implement option [1]. Should I go ahead?

**Comment by SiRumCz** [comment]
Hi dev team, any updates on this one?

**Comment by till-m** [comment]
My apologies, I am not maintaining this project anymore, hence me not responding. But I can make an exception and see this PR through.

I would suggest going with [1]. @Mithil467 could you kindly ping me when/if you've implemented that?

**Comment by Mithil467** [comment]
@till-m @nalepae I have implemented the progress bar change to type [1]. Please review.

**Comment by nalepae** [comment]
**Pandaral·lel** is looking for a maintainer!
If you are interested, please open an GitHub issue.

**Review by till-m — APPROVED** [review]
LGTM - checked that it works in a small script and in a notebook on my machine. Thanks for the PR + also the tests! Will merge soon.

**Comment by t-muser** [comment]
Thanks for the contribution :)

**Comment by Mithil467** [comment]
Thanks for the help! @till-m

**Pull request merged**
