### PR TITLE
__main__ imposition in code

### PR DESCRIPTION
**Pull request by karunakar2**
Make sure if a novice tries to access the module, he should be aware of encapsulating code within __main__ execution context, pretty much similar to that of requirements of multiprocessing in general. This will reduce wasting of time and delving into multiporcessing more.

### CODE REVIEW

**Comment by till-m** [comment]
I'm not sure why this is necessary. Could you explain?

**Comment by karunakar2** [comment]
> I'm not sure why this is necessary. Could you explain?

Hi Till,
Wondering if you could run a simple script on windows, without notebook, plain python with out the '__main__' part. doesn't work for me.
import pandas as pd
from pandarallel import pandarallel
pandarallel.initialize()

def testFn(x):
    return (x.sepal_length*x.sepal_width)/(x.petal_length*x.petal_width)

#internet based iris data
myDf = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
print(myDf.head())

res = myDf.parallel_applymap(testFn,axis=1)
print(res)

**Comment by karunakar2** [comment]
> > I'm not sure why this is necessary. Could you explain?
> 
> Hi Till, Wondering if you could run a simple script on windows, without notebook, plain python with out the '**main**' part. doesn't work for me. import pandas as pd from pandarallel import pandarallel pandarallel.initialize()
> 
> def testFn(x): return (x.sepal_length_x.sepal_width)/(x.petal_length_x.petal_width)
> 
> #internet based iris data myDf = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv') print(myDf.head())
> 
> res = myDf.parallel_applymap(testFn,axis=1) print(res)

Please ignore if the intentions are only to use on jupyter notebooks. Thanks

**Comment by till-m** [comment]
Apologies for getting back to you so late.
I think the problem here is using `applymap` instead of `apply`. Try this code:

```python
import pandas as pd
from pandarallel import pandarallel
pandarallel.initialize()

def testFn(x):
    return (x.sepal_length*x.sepal_width)/(x.petal_length*x.petal_width)

#internet based iris data
myDf = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
print(myDf.head())

res = myDf.parallel_apply(testFn,axis=1)
print(res)
```

**Pull request closed without merging**
