### PR TITLE
Fix: `parallel_apply` with data frame as an outcome returns duplicated rows

### LINKED ISSUE #74: parallel_apply(..., axis=0) return duplicated rows.
this behavior is different from pandas.

### PR DESCRIPTION
**Pull request by till-m**
Fixes #74 #187, c.f. #170.

Tests pass on my machine, though in the absence of CI I would appreciate if someone else would check that this doesn't damage anything.

### CODE REVIEW

**Comment by nalepae** [comment]
Thanks, I'll take a look.

**Comment by nalepae** [comment]
Thanks!

**Comment by nalepae** [comment]
@till-m do you have a mail/linkedin/telegram... where I can contact you?

**Comment by till-m** [comment]
Hey @nalepae, I'll drop you an email at the adress listed on your profile.

**Pull request merged**
